---
- hosts: InventoryHostList
  sudo: yes
  tasks: 
    - name: Installs epel-release
      yum: pkg=epel-release state=installed
    - name: Installs nginx web server
      yum: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx
    
  handlers:
    - name: start nginx
      service: name=nginx state=started
